# andromeda::core::interface::input::

load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

cc_library(
    name = "andromeda_interface_input_manager",
    hdrs = [
        "manager.hpp",
    ],
    deps = [
        ":andromeda_core",
        ":andromeda_interface_input_code",
    ],
)
