# andromeda::core::interface::input::code::

load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

cc_library(
    name = "andromeda_interface_input_code",
    hdrs = [
        "input.hpp",
        "key.hpp",
        "mouse.hpp",
    ],
    deps = [
        ":andromeda_core",
    ],
)
