# waker::core::system::layer::

load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

cc_library(
    name = "waker_layer_test",
    srcs = [
        "test.cpp",
    ],
    hdrs = [
        "test.hpp",
    ],
    deps = [
        ":andromeda",
    ],
)
